### ISSUE TITLE
Can't connect to local replicaset

### ISSUE THREAD

**Issue by oosthuizenr** [mingo-app/mingo#484]
Given this `docker-compose.yml` file and initialization script:
```
version: "3.8"

services:
  mongo1:
    image: mongo:5.0.12
    container_name: mongo1
    command: ["--replSet", "my-replica-set", "--bind_ip_all"]
    ports:
      - 27017:27017

  mongo2:
    image: mongo:5.0.12
    container_name: mongo2
    command: ["--replSet", "my-replica-set", "--bind_ip_all"]
```
```
rs.initiate(
  {
    _id : 'my-replica-set',
    members: [
      { _id : 0, host : "mongo1:27017" },
      { _id : 1, host : "mongo2:27017" }
    ]
  }
)
```
Resulting in this state in docker desktop:
<img width="405" alt="Screenshot 2022-09-18 at 09 54 16" src="https://user-images.githubusercontent.com/1942730/190891823-c7bf9e99-ae9f-413b-8e76-054efb636f84.png">

When trying to connect using the following settings:
<img width="816" alt="Screenshot 2022-09-18 at 09 52 14" src="https://user-images.githubusercontent.com/1942730/190891762-a6a9bf2c-e5a7-4517-8b49-565b461f0942.png">

I get the following error message:
<img width="460" alt="Screenshot 2022-09-18 at 09 52 27" src="https://user-images.githubusercontent.com/1942730/190891785-37a51b78-485c-4626-9636-f19c9a5e15e3.png">

Robo 3T connects successfully using the same mongo uri:
<img width="660" alt="Screenshot 2022-09-18 at 09 55 36" src="https://user-images.githubusercontent.com/1942730/190891855-344596d3-75db-46e7-85b3-61933ef77881.png">
<img width="318" alt="Screenshot 2022-09-18 at 09 55 44" src="https://user-images.githubusercontent.com/1942730/190891858-e35c3da1-39a7-426f-be9c-4951e0f507aa.png">
