### ISSUE TITLE
Cant connect to local mongo server created via docker

### ISSUE THREAD

**Issue by joezappie** [mingo-app/mingo#566]
### Describe the bug
I have a VSCode devcontainer project that starts up a mongodb replica server. Mongo Compass and Studio 3T both can connect via the URI:

```
mongodb://localhost:27017
```

Mingo however gives me an ECONNREFUSED error:

![image](https://user-images.githubusercontent.com/6005836/233735365-d10b8481-ce79-4df2-bc9c-7a9d58662163.png)

Really looking forward to getting this to work so I can uninstall compass and Studio 3T off my computer. Loving the cleanness of the UI and how easy it makes it to migrate data between collections, databases and other connections! Finally a good modern mongo client.

### Setup

I create the mongo DB via docker-compose in WSL:

```
  mongodb:
    hostname: mongodb
    image: mongo:5.0.9
    environment:
      MONGO_INITDB_DATABASE: zyphox
      MONGO_REPLICA_SET_NAME: rs0
    volumes:
      - mongo-data:/data/db
    restart: always
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'rs0']
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'rs0', version:1, members:[ { _id:0, host :'localhost:27017' }]}).ok || rs.slaveOk().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
```

Its started as a 1 node replica set to be able to use transactions in dev. There are no mongo users, admin DB is empty.

Does compass and 3T just add some required default parameter that I'm missing in Mingo? I tried adding `replicaSet=` parameter, and my default DB but cannot get it to connect. Works find connecting to my Atlas and Digital Ocean connections, just not my dev environment. 

```
mongodb://localhost:27017/zyphox?replicaSet=rs0
```

### Screenshots
Studio 3T
![image](https://user-images.githubusercontent.com/6005836/233734353-3d901520-d195-4336-a6eb-42079301ce82.png)

Compass
![image](https://user-images.githubusercontent.com/6005836/233734406-f7500286-f233-44b1-8b87-6514a0bf0858.png)

Mingo
![image](https://user-images.githubusercontent.com/6005836/233734465-bf338d08-ff4b-48bf-9de4-b0619e22a14d.png)

![image](https://user-images.githubusercontent.com/6005836/233734508-bf77a15a-4fc5-4d05-b945-0109c7d5d2f9.png)

![image](https://user-images.githubusercontent.com/6005836/233734535-b9155ec6-d2a0-4a1c-b190-589749d2a9a5.png)

### Desktop (please complete the following information):
 - Mingo version: 1.12.1
 - OS: Windows 11 - 22621.1555
 - WSL version: 1.2.0.0 / Ubuntu 22.04.1 LTS
